### ISSUE TITLE
affects all other themes

### ISSUE THREAD

**Issue by jans-code** [mohirio/jupyterlab-horizon-theme#19]
All jupyterlab themes now get a

```css
body {
  background: #232530;
}
```

when jupyterlab-horizon-theme 4.0.1 is installed.
